### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [zoeypeterson/frances-ellen-watkins-harper_iola-leroy#1]
- [x] Please run `se clean .` again. It wants to move some stuff in chapter 30. I recommend doing this after fixing the other issues.

- [x] Please run `se typogrify .` again. It looks like it needs to add no-break spaces.

- [x] In Chapter 6, `<abbr class="time">` needs "eoc" in the class for "4 a.m."

- [x] In Chapter 14, move the single left quote before "Dear Brother" out of the `<b>`.

- [x] In Chapter 14, move the `valediction` and `z3998:sender z3998:signature` to their parent `<p>` elements.

- [x] In the local.css, because the styling for the introduction `<footer>` and the letter `<footer>` is the same, you can just target "footer" (It would look exactly like the CSS in [section 7.7.3.2.](https://standardebooks.org/manual/1.4.0/single-page#7.7.3.2)).

**Comment by zoeypeterson** [comment]
Thanks for catching these, Emma. 

I've made all the changes, but I do have one question about moving the `z3998:sender z3998:signature` to its parent `<p>` element. That's what I'd done initially, but the hair space between the `’` and the `”` kept rendering as a square on my Kobo. (See screenshot.)

I'd added those `<span>` elements to get around the problem, but perhaps there is a better way. Any thoughts?

![screen_023](https://user-images.githubusercontent.com/76541942/108763284-0ccdce80-7506-11eb-9784-86b17d0ebb81.jpg)

**Comment by zoeypeterson** [comment]
Hi Alex,

When I did my initial proofread on a couple of Kobos, I noticed that errant square after the signature. (See above.) I tried to cheat it by adding a `<span>` tag:

`<p>‘<span epub:type="z3998:sender z3998:signature">Iola Leroy</span>.’ ”</p>`

That fixed it on the Kobo, but caused problems for Emma when she did her checks. Is there a way to achieve fix this that doesn't produce this buggy character on Kobos?

**Comment by acabal** [comment]
The font you selected doesn't have the hair space character. This is something to report to Kobo if you can.  You can try an alternate font to see if the different font has the character. But, don't try to change the HTML just to get around this; this is a Kobo bug, not a problem with the original HTML.

**Comment by acabal** [comment]
Additional issues:

- Missing `<abbr class="name">` on initial in dedication
- There is an endnotes.xhtml file but it doesn't contain any endnotes. It should be called `note.xhtml`, the ID attribute has to match, and the and epub:type semantic has to be changed to something more appropriate, as `chapter` is incorrect
- In the poem in chapter 30 `epub:type="title"` is incorrect as that only applies to ToC entries. Remove that semantic and also `<b>`, and target that `<p>` for small caps in the CSS

**Comment by zoeypeterson** [comment]
I had the font set to "Publishers default," but I've just tested all the other fonts and it happens with all of them. I suspect that the device does have the hair space character since it works everywhere else throughout the book, but perhaps it doesn't know how to render a small caps hair space.

Anyway, thanks for looking. I'll definitely report it to Kobo.

**Comment by zoeypeterson** [comment]
Thanks for catching those additional issues. I'll take care of those tomorrow.
